In [80]:
#importing the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [81]:
#importing the dataset

data=pd.read_csv("/content/kidney_disease.csv")

In [82]:
data

id   age    bp     sg   al   su  ...   dm cad appet   pe  ane  classification
0      0  48.0  80.0  1.020  1.0  0.0  ...  yes  no  good   no   no             ckd
1      1   7.0  50.0  1.020  4.0  0.0  ...   no  no  good   no   no             ckd
2      2  62.0  80.0  1.010  2.0  3.0  ...  yes  no  poor   no  yes             ckd
3      3  48.0  70.0  1.005  4.0  0.0  ...   no  no  poor  yes  yes             ckd
4      4  51.0  80.0  1.010  2.0  0.0  ...   no  no  good   no   no             ckd
..   ...   ...   ...    ...  ...  ...  ...  ...  ..   ...  ...  ...             ...
395  395  55.0  80.0  1.020  0.0  0.0  ...   no  no  good   no   no          notckd
396  396  42.0  70.0  1.025  0.0  0.0  ...   no  no  good   no   no          notckd
397  397  12.0  80.0  1.020  0.0  0.0  ...   no  no  good   no   no          notckd
398  398  17.0  60.0  1.025  0.0  0.0  ...   no  no  good   no   no          notckd
399  399  58.0  80.0  1.025  0.0  0.0  ...   no  no  good   no   no          notckd

[400 rows x 26 columns]

In [83]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   id              400 non-null    int64  
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object 
 7   pc              335 non-null    object 
 8   pcc             396 non-null    object 
 9   ba              396 non-null    object 
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object 
 17  wc              295 non-null    obj

In [84]:
data.isnull().any() #checking for missing values


id                False
age                True
bp                 True
sg                 True
al                 True
su                 True
rbc                True
pc                 True
pcc                True
ba                 True
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv                True
wc                 True
rc                 True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [85]:
data['pcv']=data['pcv'].replace('?','')
data['wc']=data['wc'].replace('?','')
data['rc']=data['rc'].replace('?','')


In [86]:
data['pcv']=pd.to_numeric(data['pcv'])

In [87]:
data['wc']=pd.to_numeric(data['wc'])

In [88]:
data['rc']=pd.to_numeric(data['rc'])

In [89]:
data['age']=data['age'].fillna(value=data['age'].mean())

In [90]:
data['bp']=data['bp'].fillna(value=data['bp'].mean())

In [91]:
data['sg']=data['sg'].fillna(value=data['sg'].mean())

In [92]:
data['al']=data['al'].fillna(value=data['al'].mean())

In [93]:
data['su']=data['su'].fillna(value=data['su'].mean())

In [94]:
data['rbc']=data['rbc'].fillna(value=data['rbc'].mode().iloc[0])

In [95]:
data['pc']=data['pc'].fillna(value=data['pc'].mode().iloc[0])

In [96]:
data['pcc']=data['pcc'].fillna(value=data['pcc'].mode().iloc[0])

In [97]:
data['ba']=data['ba'].fillna(value=data['ba'].mode().iloc[0])

In [98]:
data['bgr']=data['bgr'].fillna(value=data['bgr'].mean())

In [99]:
data['bu']=data['bu'].fillna(value=data['bu'].mean())

In [100]:
data['sc']=data['sc'].fillna(value=data['sc'].mean())

In [101]:
data['sod']=data['sod'].fillna(value=data['sod'].mean())

In [102]:
data['pot']=data['pot'].fillna(value=data['pot'].mean())

In [103]:
data['hemo']=data['hemo'].fillna(value=data['hemo'].mean())

In [104]:
data['pcv']=data['pcv'].fillna(value=data['pcv'].mode().iloc[0])

In [105]:
data['wc']=data['wc'].fillna(value=data['wc'].mode().iloc[0])

In [106]:
data['rc']=data['rc'].fillna(value=data['rc'].mode().iloc[0])

In [107]:
data['htn']=data['htn'].fillna(value=data['htn'].mode().iloc[0])

In [108]:
data['dm']=data['dm'].fillna(value=data['dm'].mode().iloc[0])

In [109]:
data['cad']=data['cad'].fillna(value=data['cad'].mode().iloc[0])

In [110]:

data['appet']=data['appet'].fillna(value=data['appet'].mode().iloc[0])

In [111]:
data['pe']=data['pe'].fillna(value=data['pe'].mode().iloc[0])

In [112]:
data['ane']=data['ane'].fillna(value=data['ane'].mode().iloc[0])

In [113]:
data['pcv']=pd.to_numeric(data['pcv'])

In [114]:
X=data.iloc[:,1:9].values
X

array([[48.0, 80.0, 1.02, ..., 'normal', 'normal', 'notpresent'],
       [7.0, 50.0, 1.02, ..., 'normal', 'normal', 'notpresent'],
       [62.0, 80.0, 1.01, ..., 'normal', 'normal', 'notpresent'],
       ...,
       [12.0, 80.0, 1.02, ..., 'normal', 'normal', 'notpresent'],
       [17.0, 60.0, 1.025, ..., 'normal', 'normal', 'notpresent'],
       [58.0, 80.0, 1.025, ..., 'normal', 'normal', 'notpresent']],
      dtype=object)

In [115]:
data.isnull().any()

id                False
age               False
bp                False
sg                False
al                False
su                False
rbc               False
pc                False
pcc               False
ba                False
bgr               False
bu                False
sc                False
sod               False
pot               False
hemo              False
pcv               False
wc                False
rc                False
htn               False
dm                False
cad               False
appet             False
pe                False
ane               False
classification    False
dtype: bool

In [116]:
x=data.iloc[:,1:25]

In [117]:
type(x)

pandas.core.frame.DataFrame

In [118]:


x=data.iloc[:,1:25].values

In [119]:
x

array([[48.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [7.0, 50.0, 1.02, ..., 'good', 'no', 'no'],
       [62.0, 80.0, 1.01, ..., 'poor', 'no', 'yes'],
       ...,
       [12.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [17.0, 60.0, 1.025, ..., 'good', 'no', 'no'],
       [58.0, 80.0, 1.025, ..., 'good', 'no', 'no']], dtype=object)

In [120]:
y=data.iloc[:,25:].values

In [121]:
from sklearn.preprocessing import LabelEncoder

In [122]:
lb=LabelEncoder()

In [123]:
x[:,5]=lb.fit_transform(x[:,5])

In [124]:
x

array([[48.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [7.0, 50.0, 1.02, ..., 'good', 'no', 'no'],
       [62.0, 80.0, 1.01, ..., 'poor', 'no', 'yes'],
       ...,
       [12.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [17.0, 60.0, 1.025, ..., 'good', 'no', 'no'],
       [58.0, 80.0, 1.025, ..., 'good', 'no', 'no']], dtype=object)

In [125]:
x[:,6]=lb.fit_transform(x[:,6])

In [126]:
x[:,7]=lb.fit_transform(x[:,7])

In [127]:

x[:,8]=lb.fit_transform(x[:,8])

In [128]:

x[:,18]=lb.fit_transform(x[:,18])

In [129]:
x[:,19]=lb.fit_transform(x[:,19])

In [130]:
x[:,20]=lb.fit_transform(x[:,20])

In [131]:
x[:,21]=lb.fit_transform(x[:,21])

In [132]:
x[:,22]=lb.fit_transform(x[:,22])

In [133]:
x[:,23]=lb.fit_transform(x[:,23])

In [134]:
y[:,0]=lb.fit_transform(y[:,0])

In [135]:
x[0:5,:]

array([[48.0, 80.0, 1.02, 1.0, 0.0, 1, 1, 0, 0, 121.0, 36.0, 1.2,
        137.52875399361022, 4.627243589743592, 15.4, 44.0, 7800.0, 5.2,
        1, 1, 0, 0, 0, 0],
       [7.0, 50.0, 1.02, 4.0, 0.0, 1, 1, 0, 0, 148.0365168539326, 18.0,
        0.8, 137.52875399361022, 4.627243589743592, 11.3, 38.0, 6000.0,
        5.2, 0, 0, 0, 0, 0, 0],
       [62.0, 80.0, 1.01, 2.0, 3.0, 1, 1, 0, 0, 423.0, 53.0, 1.8,
        137.52875399361022, 4.627243589743592, 9.6, 31.0, 7500.0, 5.2, 0,
        1, 0, 1, 0, 1],
       [48.0, 70.0, 1.005, 4.0, 0.0, 1, 0, 1, 0, 117.0, 56.0, 3.8, 111.0,
        2.5, 11.2, 32.0, 6700.0, 3.9, 1, 0, 0, 1, 1, 1],
       [51.0, 80.0, 1.01, 2.0, 0.0, 1, 1, 0, 0, 106.0, 26.0, 1.4,
        137.52875399361022, 4.627243589743592, 11.6, 35.0, 7300.0, 4.6,
        0, 0, 0, 0, 0, 0]], dtype=object)

In [136]:
from sklearn.model_selection import train_test_split

In [137]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.35,random_state=1)

In [138]:
y_train =y_train.flatten()
y_test = y_test.flatten()

In [139]:


y_train = y_train.astype(np.float)
y_test = y_test.astype(np.float)


In [140]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [141]:
from joblib import dump
dump(sc,"scale.save")

['scale.save']

In [142]:
from sklearn.tree import DecisionTreeClassifier
dt= DecisionTreeClassifier(criterion='entropy',random_state=0)
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [143]:
y_pred=dt.predict(x_test)
y_pred

array([1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       0., 0., 0., 1.])

In [144]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9714285714285714

In [ ]:
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)